name: Sync Fork

on:
  schedule:
    - cron: '* * * * *'
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout fork repository
      uses: actions/checkout@v2
      with:
        repository: ${{ github.repository }}
        token: ${{ secrets.GITHUB_TOKEN }}
        ref: remapped

    - name: Add upstream remote
      run: git remote add upstream https://github.com/HibiscusMC/HMCCosmetics.git

    - name: Fetch upstream changes
      run: git fetch upstream

    - name: Merge upstream changes into fork
      run: git merge upstream/remapped --allow-unrelated-histories

    - name: Push changes to fork
      run: git push origin remapped
